const mockEvents = 

{
    city: {
      id: 1007700,
      city: 'München',
      lat: 48.14,
      lon: 11.58,
      state: '',
      country: 'de',
      zip: 'meetup3',
      member_count: 1257
    },
    events: [
      {
        local_time: '15:00',
        local_date: '2019-10-27',
        link: 'https://www.meetup.com/Djembe-and-Percussion-Fun-Munchen/events/lqqtbryznbkc/',
        visibility: 'public_limited',
        group: {
          created: 1376421848000,
          name: 'Djembe and Percussion Fun Muenchen',
          id: 9795322,
          join_mode: 'approval',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Djembe-and-Percussion-Fun-Munchen',
          who: 'Munich Percussionists',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        waitlist_count: 0,
        yes_rsvp_count: 1,
        duration: 14400000,
        time: 1572184800000,
        utc_offset: 3600000,
        name: 'Sonniger Sonntag - E-Garten',
        id: 'lqqtbryznbkc'
      },
      {
        local_time: '19:00',
        local_date: '2019-10-31',
        link: 'https://www.meetup.com/Djembe-and-Percussion-Fun-Munchen/events/265750801/',
        visibility: 'public_limited',
        group: {
          created: 1376421848000,
          name: 'Djembe and Percussion Fun Muenchen',
          id: 9795322,
          join_mode: 'approval',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Djembe-and-Percussion-Fun-Munchen',
          who: 'Munich Percussionists',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        waitlist_count: 0,
        yes_rsvp_count: 1,
        duration: 7200000,
        time: 1572544800000,
        utc_offset: 3600000,
        name: 'Neue Regeln für neue Mitglieder',
        id: '265750801'
      },
      {
        created: 1564129835000,
        duration: 7200000,
        id: 'qbmqfryznbjc',
        name: 'Shut Up & Write!™ Munich',
        rsvp_limit: 15,
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1572075000000,
        local_date: '2019-10-26',
        local_time: '09:30',
        rsvp_open_offset: 'PT163H30M',
        updated: 1564129835000,
        utc_offset: 7200000,
        waitlist_count: 11,
        yes_rsvp_count: 10,
        venue: {
          id: 25966475,
          name: 'Bellevue München',
          lat: 48.160736083984375,
          lon: 11.563915252685547,
          repinned: false,
          address_1: 'Schleißheimer Str. 142a',
          city: 'München',
          country: 'de',
          localized_country_name: 'Germany'
        },
        group: {
          created: 1532540208000,
          name: 'Shut Up & Write!® Munich',
          id: 29351354,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'shutupandwritemunich',
          who: 'Writers',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/shutupandwritemunich/events/qbmqfryznbjc/',
        description: '<p>Join us for an hour of writing! We’ve discovered that it’s strikingly helpful to write with other writers. See if it’s true for you at 09:30 on Saturday.</p> <p>Be it a book, blog, script, essay, dissertation, resume, melody, poem or just plain work stuff, you are invited to write it with us. No one will see what you\'ve written or give you unsolicited advice. Instead of just thinking about writing, come and get some real writing done.<br/>SCHEDULE:<br/>09:30 - SESSION 1: quick intros.<br/>09:45 - timer starts: write for 1 hour.<br/>10:45 - chat / take off / keep writing for another timed hour (starting at ~11:15).</p> <p>OPTIONAL SOCIALIZING happens after we\'re done with the first/second writing hour. Writing is very solitary. Connecting (and sometimes even commiserating) with other writers is a cool thing.<br/>BEING LATE IS OKAY: just show up and get settled, then check-in with me after the session. (I’ll be the person with the Shut Up &amp; Write! sign.) If you were on time, please be willing to make room for the friendly latecomer.<br/>Happy writing and I look forward to seeing you!</p> <p>What Should I Bring?<br/>Whatever you need to be able to write!<br/>Bring earbuds/earplugs if you want to block the cafe’s overhead music or the occasional conversation by other patrons.<br/>There should be enough sockets to charge your devices, but make sure to charge them just in case! :)</p> <p>Other Important Details:<br/>GUIDELINES: Please thank our hosts by purchasing something.<br/>FUTURE LOCATIONS: If you have ideas about where and when we should meet, please share them! :)<br/>If you\'re on the waiting list, but still really really want to come, feel free to drop by — but in case we end up being too large of a group to manage, or we don\'t find enough free seats, the priority is on the folks with the \'going\' RSVPs!</p> ',
        how_to_find_us: 'Look for the Shut up & Write! sign or ask for Arnaud ',
        visibility: 'public',
        pro_is_email_shared: false,
        member_pay_fee: false
      },
      {
        local_time: '15:00',
        local_date: '2019-11-10',
        link: 'https://www.meetup.com/Monthly-Creative-Jam/events/265881572/',
        visibility: 'public_limited',
        group: {
          created: 1571595318000,
          name: 'Monthly Creative Jam in Munich',
          id: 32916012,
          join_mode: 'approval',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Monthly-Creative-Jam',
          who: 'Jammers',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        waitlist_count: 0,
        yes_rsvp_count: 2,
        duration: 10800000,
        time: 1573394400000,
        utc_offset: 3600000,
        name: '1st jam trial',
        id: '265881572'
      },
      {
        created: 1567509854000,
        duration: 10800000,
        fee: {
          accepts: 'cash',
          amount: 5,
          currency: 'EUR',
          description: '',
          label: 'Price',
          required: false
        },
        id: '264518852',
        name: 'Handlettering Workshop for Beginners',
        rsvp_limit: 20,
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1573308000000,
        local_date: '2019-11-09',
        local_time: '15:00',
        updated: 1567754879000,
        utc_offset: 3600000,
        waitlist_count: 26,
        yes_rsvp_count: 20,
        venue: {
          id: 26506384,
          name: 'Biedersteiner Str. 30',
          lat: 48.16643142700195,
          lon: 11.596017837524414,
          repinned: false,
          address_1: 'Biedersteiner Str. 30',
          city: 'München',
          country: 'de',
          localized_country_name: 'Germany'
        },
        group: {
          created: 1548683240000,
          name: 'Munich Art Meetup',
          id: 31031871,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Munich-Art-Meetup',
          who: 'Members',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/Munich-Art-Meetup/events/264518852/',
        description: '<p>FOR WHO:<br/>Everyone interested in learning Handlettering</p> <p>THE WORKSHOP:<br/>3pm - 5pm<br/>- Introduction round<br/>- What is handlettering?<br/>- Understanding the principles &amp; Warm up<br/>- Basic strokes<br/>- Composition of letters<br/>- Writing the alphabet</p> <p>5pm<br/>Final project: write your name and a phrase</p> <p>Starter Kit: 5€<br/>It includes the basic materials: brush pen, guide, paper</p> <p>Since there are so many different tools for handlettering, it is quite confusing for a beginner to figure out what to get. That\'s why we decided to provide a starter kit for each attendee. The event itself is FREE, the 5€ just cover the starter kit.</p> <p>PLEASE BRING:<br/>- Pencil (preferably H)<br/>- Eraser<br/>- Ruler<br/>- Any brush pen that you have at home and want to try (optional)<br/>- Color paper or cardstock to write a phrase on it (optional)</p> <p>LOCATION:<br/>Biedersteiner Wohnheim, Biedersteiner Str. 30, 80805 München<br/>Enter the building, turn right and you\'ll find us!</p> <p>INSTRUCTOR:<br/>Our teacher will be the wonderful Adriana, who has been practising handlettering for a long time. She will show us the basics and guide us to letter our own compositions!<br/>Feel free to check out her work on Instagram: @letras_meigas</p> <p>We are looking forward to handletter with you!</p> ',
        how_to_find_us: 'Enter the building, turn right and you\'ll find us!',
        visibility: 'public',
        member_pay_fee: false
      },
      {
        local_time: '19:30',
        local_date: '2019-11-16',
        link: 'https://www.meetup.com/Munchen-Indie-Meetup/events/264110267/',
        visibility: 'public_limited',
        group: {
          created: 1498855310000,
          name: 'München Indie Meetup',
          id: 24765976,
          join_mode: 'approval',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Munchen-Indie-Meetup',
          who: 'Indies',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        waitlist_count: 0,
        yes_rsvp_count: 3,
        duration: 10800000,
        time: 1573929000000,
        utc_offset: 3600000,
        name: 'Deerhunter & Black Lips',
        id: '264110267'
      },
      {
        created: 1571688273000,
        duration: 7200000,
        fee: {
          accepts: 'paypal',
          amount: 5,
          currency: 'EUR',
          description: '',
          label: 'Price',
          required: true
        },
        id: '265854972',
        name: 'Music in the Round (Take 1) ',
        rsvp_limit: 10,
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1572458400000,
        local_date: '2019-10-30',
        local_time: '19:00',
        updated: 1571756077000,
        utc_offset: 3600000,
        waitlist_count: 0,
        yes_rsvp_count: 7,
        venue: {
          id: 26377511,
          name: 'creaffective GmbH',
          lat: 48.117469787597656,
          lon: 11.611420631408691,
          repinned: true,
          address_1: 'Rosenheimer Str. 189',
          city: 'München',
          country: 'de',
          localized_country_name: 'Germany'
        },
        group: {
          created: 1407016888000,
          name: 'Amateur Musicians Munich',
          id: 16147572,
          join_mode: 'approval',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'MusicLoversMeetup-Munich',
          who: 'Musicians',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/MusicLoversMeetup-Munich/events/265854972/',
        description: '<p>Do you enjoy singing and playing an acoustic instrument? Do you have songs (original or covers) that you would like to practice live in a small group setting? Interested in listening and networking with other amateur musicians?</p> <p>Music in the Round is a 2-hour acoustic music meet-up of amateur musicians (10 people maximum). We will rotate around in a circle with each musician playing/singing one song of their choice. We will continue round and round until we run out of songs or run out of time. The goals are to build confidence performing in front of others, to let your voice/playing be heard, and most of all to have a good time with others!<br/>Please join us for the Music in the Round (Take 1) on Wednesday, 30 October.</p> <p>Please take note that there are no musical instruments at the location, other than what people bring along. So ideally bring your own (acoustic) instrument. If you have a keyboard or stage piano that needs electricity, that is not a problem. But since the workshop space we are using is located in a residential area with neighbours, we can have no amplification or percussive instruments. If you are unsure what you can or cannot bring along, feel free to contact me.</p> <p>Participation will cost 5 Euros, mostly because we only have 10 spaces and want to make sure that only people serious about the event sign up. We will also provide beverages and small snacks at the event.</p> ',
        how_to_find_us: 'Ring at the door at the corner of Rosenheimer Straße and Wollanistraße, not the entrance to the apartment building.',
        visibility: 'public',
        member_pay_fee: false
      },
      {
        created: 1570533165000,
        duration: 10800000,
        id: '265499837',
        name: 'Coffee and Portrait Sketching',
        rsvp_limit: 15,
        date_in_series_pattern: false,
        status: 'upcoming',
        time: 1572181200000,
        local_date: '2019-10-27',
        local_time: '14:00',
        updated: 1570533165000,
        utc_offset: 3600000,
        waitlist_count: 22,
        yes_rsvp_count: 15,
        venue: {
          id: 26173236,
          name: 'The Tribeca Cafe',
          lat: 48.16404342651367,
          lon: 11.530770301818848,
          repinned: true,
          address_1: 'Klugstraße 134',
          city: 'München',
          country: 'de',
          localized_country_name: 'Germany'
        },
        group: {
          created: 1548683240000,
          name: 'Munich Art Meetup',
          id: 31031871,
          join_mode: 'open',
          lat: 48.13999938964844,
          lon: 11.579999923706055,
          urlname: 'Munich-Art-Meetup',
          who: 'Members',
          localized_location: 'München, Germany',
          state: '',
          country: 'de',
          region: 'en_US',
          timezone: 'Europe/Berlin'
        },
        link: 'https://www.meetup.com/Munich-Art-Meetup/events/265499837/',
        description: '<p>Are you interested in improving your art and meet like-minded people?<br/>Whether you are a beginner or a professional who is willing to share some tips- all levels are welcome :)</p> <p>What we\'ll do:<br/>- Meet at the Tribeca Cafe, have a coffee and chat<br/>- We\'ll do some sketching warm-ups (1,2 and 5 min sketches)<br/>- Volunteers of the group pose for 15 min each, so we can sketch their face<br/>- Afterwards, we\'ll exchange art and share feedback and tips with each other</p> <p>Please bring:<br/>- Your sketchbook/paper<br/>- A pencil or the medium you prefer<br/>Since we will be drawing in a cafe, you should avoid mediums like oil &amp; acryl.</p> <p>BE NICE TO THE PEOPLE ON THE WAITING LIST<br/>Please make sure to cancel your reservation as soon as possible, in case you can\'t make it, so others have a chance to join!<br/>If you don\'t cancel your reservation and don\'t show up, I have to block you from future events :(</p> ',
        how_to_find_us: 'I\'ll reserve a table for , so just ask the waiter or look for a happy group with sketchbooks and pencils :) ',
        visibility: 'public',
        member_pay_fee: false
      }
    ]
  }
export { mockEvents }